// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/business-card/CardDark.tsx": () => import("../components/mockups/business-card/CardDark.tsx"),
  "./components/mockups/business-card/CardLight.tsx": () => import("../components/mockups/business-card/CardLight.tsx")
};
