// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/header-banner/HeaderBanner.tsx": () => import("../components/mockups/header-banner/HeaderBanner.tsx"),
  "./components/mockups/quote-pdf/BrandHeader.tsx": () => import("../components/mockups/quote-pdf/BrandHeader.tsx"),
  "./components/mockups/quote-pdf/ExecutiveSummary.tsx": () => import("../components/mockups/quote-pdf/ExecutiveSummary.tsx"),
  "./components/mockups/quote-pdf/TechnicalQuote.tsx": () => import("../components/mockups/quote-pdf/TechnicalQuote.tsx")
};
