// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
const discovered = import.meta.glob<Record<string, unknown>>("../components/mockups/**/*.tsx");
export const modules: ModuleMap = Object.fromEntries(
  Object.entries(discovered)
    .filter(([path]) => path.split("/").every((segment) => !segment.startsWith("_")))
    .map(([path, loader]) => [`./${path.slice(3)}`, loader]),
) as ModuleMap;
